lenguage: node_js
node_js:
    - "9.3.0"
branches:
  only: 
  - master    

  
before_script:
  - npm install -g firebase-tools

script:
  - npm run test
  - npm install
  - npm run build
deploy:
  provider: firebase
  token:
    secure: "1//0hLLHrwsOKpDGCgYIARAAGBESNwF-L9IrHHH58sz6y9Cdf8iiQD-ehWQHTjc2DoW5s52c1RjNK4yBXGfFr6vhzaFb1zZNwFrZt7s"
  

      
    