lenguage: node_js
node_js:
    - "9.3.0"
branches:
  only: 
  - master    

  
before_script:
  - npm install -g firebase-tools

script:
  - npm run test
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token: $FIREBASE_TOKEN



      
    