
 language: node_js
node_js: 
  - "node"
  script:
    -
deploy:
  provider: firebase
  token:
    secure: "1//0hLLHrwsOKpDGCgYIARAAGBESNwF-L9IrHHH58sz6y9Cdf8iiQD-ehWQHTjc2DoW5s52c1RjNK4yBXGfFr6vhzaFb1zZNwFrZt7s"
  

      
    