lenguage: node_js
node_js:
    - "9.3.0"
branches:
  only: 
  - master    

  
before_script:
  - npm install -g firebase-tools

script:
  - npm run test
  - npm install
  - npm run build
deploy:
  provider: firebase
  token:
    secure: "1//0hZ8dZe7Fx7QACgYIARAAGBESNwF-L9IrwN9YKOqrH_2ZbWgnsViOJr8l5bXZepoHEnU9QaJt4KrefiMshbE4r4fNYvP_hc3cm_I"
    project: "sitema-inventario"

      
    