lenguage: node_js
node_js:
    - "6.13.6"
branches:
  only: 
  - master    
before_script:
  - npm install -g firebase-tools
script:
  - npm run bluid
  - npm run test
       
after_success:
    - firebase deploy --token $FIREBASE_TOKEN


      
    