lenguage: "node_js"
node_js:
    - "6.13.6"
script:
    
    - echo "Deploying"

install:
    - npm install -g firebase-tools   
after_success:
    - firebase deploy --token "$FIREBASE_TOKEN"    
    
    